name: Build Miryoku Firmware

on: [push, workflow_dispatch]

jobs:
    build:
        runs-on: ubuntu-latest
        container: qmkfm/qmk_cli
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Build Firmware
              run: |
                  git config --global --add safe.directory '*'
                  python3 -m pip install -r requirements.txt
                  make crkbd:manna-harbour_miryoku:uf2 CONVERT_TO=rp2040_ce

                  echo "=== LISTING UF2 FILES ==="
                  find . -name "*.uf2"
                  echo "========================="

            - name: Archive Firmware
              uses: actions/upload-artifact@v4
              with:
                  name: miryoku_corne_rp2040
                  path: |
                      **/*.uf2
                      **/*.hex
